apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - serviceaccount.yaml
  - deployment-payments-qr.yaml
  - service-payments-qr.yaml
  - deployment-fraud-api.yaml
  - service-fraud-api.yaml
